### ISSUE TITLE
viewer crash on shutdown sigint

### ISSUE THREAD

**Issue by reinzor** [uleroboticsgroup/yasmin#38]
```
$ ros2 run yasmin_viewer yasmin_viewer_node 
Started Yasmin viewer on http://localhost:5000
^CException in thread Thread-1 (start_subscriber):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rein/dev/harvey/system/install/lib/yasmin_viewer/yasmin_viewer_node", line 103, in start_subscriber
    rclpy.spin(self)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/__init__.py", line 244, in spin
    executor.spin_once()
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 827, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 811, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 781, in wait_for_ready_callbacks
    return next(self._cb_iter)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 689, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
Traceback (most recent call last):
  File "/home/rein/dev/harvey/system/install/lib/yasmin_viewer/yasmin_viewer_node", line 151, in <module>
    main()
  File "/home/rein/dev/harvey/system/install/lib/yasmin_viewer/yasmin_viewer_node", line 147, in main
    rclpy.shutdown()
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/__init__.py", line 134, in shutdown
    _shutdown(context=context)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/utilities.py", line 82, in shutdown
    context.shutdown()
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/context.py", line 129, in shutdown
    self.__context.shutdown()
rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:333
[ros2run]: Process exited with failure 1
```

**Comment by mgonzs13** [comment]
@reinzor thanks for the fix.
